name: Pull Request Comments

on:
  pull_request_target:
    types: [ 'opened', 'synchronize', 'reopened', 'edited' ]

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name for pull requests
  # or the commit hash for any other events.
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.sha }}
  cancel-in-progress: true

# Disable permissions for all available scopes by default.
# Any needed permissions should be configured at the job level.
permissions: {}

jobs:

  # Leaves a comment on a pull request with a link to test the changes in a WordPress Playground instance.
  playground-details:
    name: Comment on a pull request with Playground details
    runs-on: ubuntu-24.04
    permissions:
      pull-requests: write
      contents: read

    steps:
      - name: Create blueprint JSON
        id: blueprint
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          script: |
            const prNumber = context.issue.number;
            const repoOwner = context.repo.owner;
            const repoName = context.repo.repo;
            const blueprint = {
              landingPage: '/wp-admin/',
              preferredVersions: {
                php: '7.4',
                wp: 'latest',
              },
              steps: [
                {
                  step: 'mkdir',
                  path: '/tmp/pr',
                },
                {
                  step: 'writeFile',
                  path: '/tmp/pr/pr.zip',
                  data: {
                    resource: 'url',
                    url: `/plugin-proxy.php?org=${repoOwner}&repo=${repoName}&workflow=Build%20Plugin%20Zip&artifact=${repoName}&pr=${prNumber}`,
                    caption: `Downloading ${repoName} PR ${prNumber}`,
                  },
                },
                {
                  step: 'unzip',
                  zipPath: '/tmp/pr/pr.zip',
                  extractToPath: '/tmp/pr',
                },
                {
                  step: 'installPlugin',
                  pluginData: {
                    resource: 'vfs',
                    path: `/tmp/pr/${repoName}.zip`,
                  },
                }
              ]
            };
            return JSON.stringify(blueprint);
          result-encoding: string

      - name: Post Playground Preview Button
        uses: WordPress/action-wp-playground-pr-preview@c8607529dac8d2bf9a1e8493865fc97cd1c3c87b # v2
        with:
          mode: append-to-description
          blueprint: ${{ steps.blueprint.outputs.result }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
